language: java

dist: trusty

jdk:
  - openjdk8

# 'true' means do NOT do `mvn install`
# See https://docs.travis-ci.com/user/job-lifecycle/#skipping-the-installation-phase
install: true

cache:
  directories:
  - $HOME/.m2

before_install:
- bash ./.travis/setup-deploy.sh

deploy:
  - provider: script
    # skip_cleanup is to keep the artifacts from the build phase
    skip_cleanup: true
    script: bash .travis/deploy-snapshot.sh
    on:
      repo: homeaway/dropwizard-resilience4j-bundle
      branch: master
      tags: false
  - provider: script
    script: bash .travis/deploy-release.sh
    on:
      repo: homeaway/dropwizard-resilience4j-bundle
      branch: master
      tags: true
