language: java

dist: trusty

jdk:
  - openjdk11

# 'true' means do NOT do `mvn install`
# See https://docs.travis-ci.com/user/job-lifecycle/#skipping-the-installation-phase
install: true

cache:
  directories:
  - $HOME/.m2

before_install:
- bash ./.travis/setup-deploy.sh

# The deployment step will perform a maven deploy on commits or tags on the master branch to publish artifacts.
# Builds NOT triggered by a git tag will publish the SNAPSHOT artifacts.
# Builds triggered by a git tag will publish the artifacts with the given tag version.
deploy:
  - provider: script
    # skip_cleanup is to keep the artifacts from the build phase
    skip_cleanup: true
    script: bash .travis/deploy-snapshot.sh
    on:
      repo: homeaway/dropwizard-resilience4j-bundle
      branch: master
      tags: false
  - provider: script
    script: bash .travis/deploy-release.sh
    on:
      repo: homeaway/dropwizard-resilience4j-bundle
      branch: master
      tags: true
