language: java

dist: trusty

jdk:
  - openjdk8

# 'true' means do NOT do `mvn install`
# See https://docs.travis-ci.com/user/job-lifecycle/#skipping-the-installation-phase
install: true

script: mvn clean install
