name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'ExpediaGroup/dropwizard-resilience4j-bundle'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          server-id: ossrh
          server-username: SONATYPE_USERNAME # env variable for username in deploy
          server-password: SONATYPE_PASSWORD # env variable for token in deploy
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase

      - name: Build library
        run: ./mvnw clean verify

      - name: Publish library
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "New version: ${NEW_VERSION}"
          ./mvnw org.codehaus.mojo:versions-maven-plugin:2.7:set -DnewVersion=${NEW_VERSION}
          ./mvnw -DskipTests -Prelease -B deploy
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
